# Generated by Django 3.0.5 on 2020-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd_detection', '0001_initial'),
    ]

    
